---
- name: "Add repository"
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: '0644'

- name: "Install docker packages"
  ansible.builtin.yum:
    name:
      - docker-ce
    state: present
  notify: Restart docker
